app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('index');
});

Route::group(['middleware' => ['web']], function () {
	
Route::resource('task', 'TaskController');

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/



});

app/Task.php
<?php
namespace App;
use Illuminate\Database\Eloquent\Model;

class Task extends Model{
	protected $fillable = ['task_name', 'task_content'];
	protected $hidden = ['_token'];
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TaskController.php
<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Task;
use DB;
use Validator;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
	 protected $rules = [
			'task_name' => 'required',
			'task_content' => 'required'
		];
	 
    public function index()
    {
		$tasks = DB::table('tasks')->paginate(8);
		$count = 0;
		
        return view('showtasks')->with('title','All tasks')->with('tasks', $tasks)->with('count',$count);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('newtask')->with('title','New task');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
				
		
		$input = $request->all();
		//$input = $request->except('_token');
		
		$validator = Validator::make($input, $this->rules);
		
		if($validator->fails()){
			return back()->withInput()->withErrors($validator);
		}
		
        //$id = DB::table('tasks')->insertGetId($input);
		$task = new Task;
		$task->task_name = $request->input('task_name');
		$task->task_content = $request->input('task_content');
		$task->save();
		
		return redirect()->route('task.show',[$task->id])->with('title','A task');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
		$task = DB::table('tasks')->where('id','=', $id)->first();
				
        return view('showonetask')->with('title','Task')->with('task',$task);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $task = DB::table('tasks')->where('id','=', $id)->first();
		
		return view('edittask')->with('title','Edit task')->with('task',$task);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
		//$task = DB::table('tasks')->where('id','=',$id)->first();
		$task = Task::find($id);
		$input = $request->all();
		
		$validator = Validator::make($input, $this->rules);
		if($validator->fails()) return back()->withInput()->withErrors($validator);
		// $task->task_name = strip_tags($request->task_name);
		// $task->task_content = strip_tags($request->task_content);
		$task->task_name = $request->input('task_name');
		$task->task_content = $request->input('task_content');
		$task->save();
		
		return redirect()->route('task.show',[$task->id])->with('title','Show task');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $task = Task::find($id);
		if(count($task) > 0){
			$task->delete();
			return redirect()->route('task.index')->with('message', 'Task deleted');
		}
		return back()->with('error', 'Not deleted');		
    }
}

resources/views/edittask.blade.php
@extends('layouts.master')

@section('content')
	<div class="row">
		<div class="col-md-6">
			@if(count($task)>0)
				{!! Form::model($task,['route'=>['task.update',$task->id], 'method'=>'PUT', 'id'=>'taskEditForm', 'class'=>'form-horizontal']) !!}
			<div class="form-group">
				{!! Form::label('task_name', 'Task name', ['class'=>'control-label']) !!}
				{!! Form::text('task_name', null, ['class'=>'form-control']) !!}
				@if($errors->has('task_name')) <p class="help-block alert alert-danger">{!! $errors->first('task_name') !!}</p>@endif
			</div>
			<div class="form-group">
				{!! Form::label('task_content', 'Task content', ['class'=>'control-label'] ) !!}
				{!! Form::textarea('task_content', null, ['class' => 'form-control'] ) !!}
				@if ($errors->has('task_content')) <p class="help-block alert alert-danger">{{ $errors->first('task_content') }}</p>@endif
			</div>
			<div class="form-group">
				{!! Form::submit('Save', ['class'=>'btn btn-primary']) !!}
			</div>
				{!! Form::close() !!}				
			@else
				<p>No tasks found.</p>
			@endif
		</div>		
	</div>
@endsection

resources/views/index.blade.php
@extends('layouts.master')
@section('content')	
	<div class="row">
		<div class="col-md-12 taskLink">
			<p>Check: {!! link_to_route('task.index', 'Task List', $arguments = [], $parameters = []) !!}</p>
		</div>
	</div>
@endsection

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="lt">
<head>
	<meta charset="UTF-8">
	<title>@if(isset($title)){!! $title !!}@else Task manager @endif</title>
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">	
	<link rel="stylesheet" type="text/css" href="{!! asset('css/styles.css') !!}">
</head>
<body>
	<div class="container main">
		<header>
			<h1>Task manager</h1>
			<nav>@include('partials.menu')</nav>
		</header>
		@if(session('message'))
			<p class="alert alert-success">{{ session('message') }}</p>
			{{ Session::forget('message') }}
		@endif
		@yield('content')
	</div>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<script src="{!! asset('js/main.js') !!}"></script>
</body>
</html>

resources/views/newtask.blade.php
@extends('layouts.master')
@section('content')
	<div class="row">
		<div class="col-md-6">			
				{{ Form::open(['route'=>'task.store'],['class'=>'form-horizontal task-form']) }}
				<div class="form-group">
					{{ Form::label('task_name',"Task name",['class'=> 'control-label']) }}
					{{Form::text('task_name',null, ['class'=> 'form-control'])}}
					@if ($errors->has('task_name')) <p class="help-block alert alert-danger">{{ 		$errors->first('task_name') }}</p>
					@endif
				</div>
				<div class="form-group">
					{{Form::label('task_content', 'Task content',['class'=> 'control-label'])}}
					{{Form::textarea('task_content',null, ['class'=> 'form-control'])}}
					@if($errors->has('task_content')) <p class="help-block alert alert-danger">{{ $errors->first('task_content') }}</p>
					@endif
				</div>
				<div class="form-group">
					{{Form::submit('Create',['class'=>'btn btn-primary'])}}
				</div>
				{{Form::close()}}
		</div>
	</div>

@endsection

resources/views/partials/menu.blade.php
{!! link_to('/', 'Home',$arguments = ["class"=>"btn btn-default"]) !!}
{!! link_to_route('task.index', 'All tasks',$arguments = [], $parameters = ["class"=>"btn btn-default"]) !!}
{!! link_to_route('task.create', 'Create new task',$arguments = [], $parameters = ["class"=>"btn btn-default"]) !!}

resources/views/showonetask.blade.php
@extends('layouts.master')
@section('content')	
	<div class="row oneTask">
		<div class="col-md-5 oneTaskBody">
			@if($task)
				<h3>{{ $task->task_name }}</h3>
				<p class="taskText">{{ $task->task_content }}</p>
				<div class="dates">
					<p><b>Created at:</b> <span>{{ $task->created_at }}</span></p>
					<p><b>Last update:</b> <span>{{ $task->updated_at }}</span></p>
				</div>
				<div class="editBtnGroup">
					{!! link_to_route('task.edit', 'Edit task', $arguments = [$task->id], $parameters = ["class"=>"btn btn-default editBtn"]) !!}
					<form action="{!! route('task.destroy',['id'=>$task->id]) !!} " method="POST" id="delForm">
						{!! csrf_field() !!}
						{!! method_field('delete') !!}
						<div class="form-group">
							<input type="submit" name="submit" value="delete" class="btn btn-danger delBtn">
						</div>
					</form>
				</div>
			@else	
				<p>No task found.</p>
			@endif
		</div>
	</div>
@endsection

resources/views/showtasks.blade.php
@extends('layouts.master')

@section('content')
	<div class="row">
		<div class="col-md-8">
			@if(count($tasks)>0)
				
					<ul class="list-unstyled taskList">
						@foreach($tasks as $key=>$task)					
							<li><b>{!! ++$count !!}</b><span>{{ link_to_route('task.show',$task->task_name, $arguments = [$task->id] ) }}</span>{{ link_to_route('task.edit','edit',$arguments = [$task->id], $parameters = ['class'=>'btn btn-default taskListEditBtn']) }}							
							</li>
						@endforeach
					</ul>
				
			@else
				<p>No tasks found.</p>
			@endif
			@if($tasks) {{ $tasks->render() }} @endif
		</div>
		
	</div>

@endsection